apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unknown-kafka-consumer
  name: unknown-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unknown-kafka-consumer
  template:
    metadata:
      labels:
        app: unknown-kafka-consumer
    spec:
      containers:
      - name: unknown-kafka-consumer
        image: quay.io/strimzi-examples/java-kafka-consumer:latest
        env:
          # Notice how there are no secrets here linking our consumer with our Kafka user
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9093
          - name: TOPIC
            value: my-topic
          - name: GROUP_ID
            value: java-kafka-consumer
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000000"

